apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook
  namespace: phonebook-app
  labels:
    app: phonebook-app
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebook-app
  template:
    metadata:
      labels:
        app: phonebook-app
        env: demo
    spec:
      containers:
      - name: phonebook-app
        image: 127.0.0.1:5000/phonebook-app
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-config
          mountPath: /app/config
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: backend-url
            path: .env

