version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    links:
      - jenkins_slave1
    container_name: jenkins
    hostname: jenkins
    networks:
      minikube:
        ipv4_address: 192.168.49.4
    volumes:
      - "./data:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins_slave1:
    image: jenkins/ssh-agent:latest-jdk11-1
    privileged: true
    user: root
    environment:
      - "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPbDB0orDJEiz79ySs7ptvyk0I6qFSWewxNoB3QTVdFm/37DsNmBKTPg7yIDss1FcGgoNMyMS7fKks8lvrRSHX69o7jKxJV8EOPKs9oTfl4xbTV+BrxHE+HDjbUxaz2ZUzArJYTCbLh7aEY0tAjuo1LuVjsqAk/MuN/h/XVJ7F/YgwzdMUlWlzuTSZtPZ4KGKXA3Zx9qgyjsh6ADE7ASRsgavXsAGHodNW5eSBv9/TV2mruUbhiBttNVevjSVfIRLRmk/Nfl+nB4kyRY7vtKzwJVK1EjWBHW1nuSqkArMyf/dsajKl7obSjY+HIEZ5YblRWt/U62B5bZnVe9IqZyLj7+HRClfyU3HYRs47tHZChtsvgMFUqUCOFHP5HjDqz4MNM18b+hn7ofbPiEVrxfB3Zv9pkdOJKydT+M8MS70MudV8j3Z1JIzo1p/Tz+WkXks6Fuz4S3YDQ/iswNnLjQ2nUC8WKt7efPXWcphy3yHgPN6ZgBxVG0KxsoKJWN3KKA8= squ_a@DESKTOP-V810M7I
"
    networks:
      minikube:
        ipv4_address: 192.168.49.3
    volumes:
      - "./kubectl-config:/home/jenkins/.kube"
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    environment:
      - "REGISTRY_HTTP_ADDR=192.168.49.5:5000"
    ports:
      - "5000:5000"
    networks:
      minikube:
        ipv4_address: 192.168.49.5

networks:
    minikube:
      external: true

